### PR TITLE
add a basic gitIgnore

### PR DESCRIPTION
**Pull request by SadatAnwar**
Git ignore

### CODE REVIEW

**Comment by SadatAnwar** [comment]
@hageldave I thought this would come in handy :)

**Comment by hageldave** [comment]
@SadatAnwar Hey, that's rly cool. Never had a pull request before. Currently the latest version of this project is on the development branch (devel). If you could switch to that branch (`git checkout devel`) and do another pull request that would be awesome ;)

**Comment by SadatAnwar** [comment]
@hageldave hey no worries, Ill rebase on to devel and then ping you here... Nice name though (devel)? 
dev-david-hagel

**Comment by SadatAnwar** [comment]
there you go! Git hub makes it super easy to do stuff like that! :)

**Comment by SadatAnwar** [comment]
created another #8

**Pull request closed without merging**
